sudo: required
dist: xenial

language: erlang

otp_release:
 - 20.3.8.5
 - 21.1.4
 - 21.2.4

install: "true"

before_install:
  - wget https://s3.amazonaws.com/rebar3/rebar3
  - chmod u+x ./rebar3

script:
  - env
  - ./rebar3 compile
  - ./rebar3 do xref, ct, coveralls send

notifications:
  slack:
    secure: "SPRWSBN+b2Jj4Tokcc/wVpoN+1o2kkf2bJf3OSlsn9dtwUoNSF6m4USFa0RvkJphKKswpfgCC/8fRX73ZJKQtbSycThtEG0bHE5uyTS/JzYr8QPqh11DEsVnP7iboIu3JR7U8CJTbKcbsJz1jE1ZZio/ENYErv26xyObjDYCPxzu2nb3nBLTXYWLm2vonHFX2Pga5Rv6HatH6+KIOCWBvon49j+wU6n480KagNNy9DS2qJ0yvOr/19AMAQZX1uHXGHILeiorw3wIDjngi87JLX0pG5mIo9WEl0xQZtqYajId0akDoudcU3CK3UvGffVZUEiJ/uTog85KPgFJBwg7eJr2jP988EFO4Nn1pRUQGqMfmHvI5zhzKFpuEpvRv0SIrwMOYFTqsngf4GGTIAWRmPXeRQ0zNzwifnPaQKjB0pVjUmTloZRLiR9xE5aDPJqS6DYRCJSpAOMZg1ldZmR4kb03DCytw6ijCFbR9XthCtpuf5quCRUoWxVKcG1hv3dNbAleeJfOoKqMYLs+wzvrUPvst4x6WgQJJr0XyvhVy80aaltOgiX3gQN9AcoHBy0BbBpqm/FegY2X9MgbmNy64suy7hbDt12fITPnNAfwF955Gfua9Vz9l7CLoNH2qBpQwPLdneedWjLOdFeKojlDSjcx+PSMPHgoVC6YbeED2Xk="
